### ISSUE TITLE
Hello, are you thinking about multilingualism for Primal Stage 

### ISSUE THREAD

**Issue by canniand** [nanokulonq/PrimalStage#1]
I use this translation, I don't know much English myself

**Comment by canniand** [comment]
Also, can I transfer your mod to mc Encyclopedia? https://www.mcmod.cn/ I'll credit the original author and add download links for curseforge and modrinth

**Comment by nanokulonq** [comment]
@canniand yes, you can

**Comment by nanokulonq** [comment]
> Also, can I transfer your mod to mc Encyclopedia? https://www.mcmod.cn/ I'll credit the original author and add download links for curseforge and modrinth

yes, you can

**Comment by nanokulonq** [comment]
@canniand if you want to help translate the mod, you can just send me the lang file and I will add it

**Comment by canniand** [comment]
> 如果你想帮助翻译这个模组，你可以把lang文件发给我，我会添加它

Hello, thank you for agreeing to my request, this is my translated lang file, but I don't promise that I can translate the best

**Comment by canniand** [comment]
[zh_CN.zip](https://github.com/nanokulonq/PrimalStage/files/11419247/zh_CN.zip)
The most is lang file trouble you to decompress it yourself

**Comment by nanokulonq** [comment]
> [zh_CN.zip](https://github.com/nanokulonq/PrimalStage/files/11419247/zh_CN.zip) The most is lang file trouble you to decompress it yourself


Thanks, updated the mod
