### ISSUE TITLE
Can't forge items with other mallet

### ISSUE THREAD

**Issue by fluor4te** [nanokulonq/PrimalStage#12]
I added mallets from ingotcraft to tag "primalstage:mallets" to support them, in REI it shows that i can process items with them, but in fact i can't
![2023-12-05_23 23 20](https://github.com/nanokulonq/PrimalStage/assets/70164400/7e5bf44d-b172-409c-80e3-7a1dfe51d9a4)

**Comment by fluor4te** [comment]
added to this tag through kubejs

**Comment by nanokulonq** [comment]
> I added mallets from ingotcraft to tag "primalstage:mallets" to support them, in REI it shows that i can process items with them, but in fact i can't ![2023-12-05_23 23 20](https://private-user-images.githubusercontent.com/70164400/288161037-7e5bf44d-b172-409c-80e3-7a1dfe51d9a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMTcyMTAsIm5iZiI6MTcwMjExNjkxMCwicGF0aCI6Ii83MDE2NDQwMC8yODgxNjEwMzctN2U1YmY0NGQtYjE3Mi00MDljLTgwZTMtN2ExZGZlNTFkOWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDEwMTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkY2NmZTc2Mjk5YzFhYzM1YjFjMGYwYzk2N2VlOGM0ZTgxYjVjZmFmYTc5ZmM2YzM2MmI0YmM0ZjFjODZjNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r3SsGUrmf2AyFskU8Od_10Vu8UQC4u0j4-P46ot_064)

fixed
