### ISSUE TITLE
EMI Compatibility [Feature Request]

### ISSUE THREAD

**Issue by KirboSoftware** [nanokulonq/PrimalStage#2]
Hey, will Primal Stage will get [EMI](https://www.curseforge.com/minecraft/mc-mods/emi) compatibility in the future? or is that something you will not add?  

If not, would you mind if I made a PR to integrate that into your mod?

I wish you a lovely day and thanks for reading <3

**Comment by nanokulonq** [comment]
> Hey, will Primal Stage will get [EMI](https://www.curseforge.com/minecraft/mc-mods/emi) compatibility in the future? or is that something you will not add?
> 
> If not, would you mind if I made a PR to integrate that into your mod?
> 
> I wish you a lovely day and thanks for reading <3

ok, i'll add it soon

**Comment by KirboSoftware** [comment]
Thank you! I wish you a lovely day

**Comment by nanokulonq** [comment]
> Thank you! I wish you a lovely day

Integration added
