### ISSUE TITLE
Config Suggestions

### ISSUE THREAD

**Issue by milkev** [nanokulonq/PrimalStage#4]
As a fan of config & customization, I thought I'd recommend a few config options;

TreesRequireTool - boolean defining if the player is required to have an axe to break a tree or not. I'll be honest this is the primary one I want, as most of the mods content seems really cool, I just want my players to be able to mine tree's normally.

AnimalPeltInsteadOfLeather - boolean defining if animals should drop animal pelts instead of leather.

WoolScrapInsteadOfWool - boolean defining if sheep should drop wool scrap instead of wool.

SpawnTwigsAndPebbles - boolean defining if twigs and pebbles should be generated in the world. Primarily could be a performance concern for people on lower end hardware.

**Comment by nanokulonq** [comment]
> As a fan of config & customization, I thought I'd recommend a few config options;
> 
> TreesRequireTool - boolean defining if the player is required to have an axe to break a tree or not. I'll be honest this is the primary one I want, as most of the mods content seems really cool, I just want my players to be able to mine tree's normally.
> 
> AnimalPeltInsteadOfLeather - boolean defining if animals should drop animal pelts instead of leather.
> 
> WoolScrapInsteadOfWool - boolean defining if sheep should drop wool scrap instead of wool.
> 
> SpawnTwigsAndPebbles - boolean defining if twigs and pebbles should be generated in the world. Primarily could be a performance concern for people on lower end hardware.

thx, i will add it soon
