### ISSUE TITLE
[Question] Port Related

### ISSUE THREAD

**Issue by accessdenied0** [nanokulonq/PrimalStage#6]
Hey!

I saw your mod and was overjoy since I really searched for something like it for an (private for now) pack I am working on...
But sadly I saw that it was only for Fabric, which in return doesn't has like half of the mods I would like or need...
I am sure you read this question a dozen times, since alot of people wanna cross loader compats... 

But I since I really could use your mod, I was curious if there are any chances that you can make a forge port?
- or -
If you allow, to make a fork and let it get ported/port it myself, of course with credit to you as the creator.

I thank you for your reply.

**Comment by nanokulonq** [comment]
> 

Yeah. u can make a fork
