### ISSUE TITLE
Flint tools are better than wood and stone

### ISSUE THREAD

**Issue by KirboSoftware** [nanokulonq/PrimalStage#7]
Like the title says, flint tools from PS are having quite some durability. Wood has 59 and flint for some reason has 225, is this an oversight or is this intended behaviour?

**Comment by nanokulonq** [comment]
> Like the title says, flint tools from PS are having quite some durability. Wood has 59 and flint for some reason has 225, is this an oversight or is this intended behaviour?

This is the intended behavior =)

**Comment by KirboSoftware** [comment]
Wouldn't it make more sense to have it lower than wood's durability since it's normally considered a "tier" lower than wood and because you can't get wood until you can craft a flint tool, it feels more odd than having it almost as durable as iron.
